version: "2"
linters:
  enable:
    - errorlint
    - gocritic
    - misspell
    - nonamedreturns
    - testifylint
  settings:
    errorlint:
      errorf: true
      errorf-multi: true
      asserts: true
      comparison: true
    testifylint:
      enable:
        - bool-compare
        - compares
        - empty
        - error-is-as
        - error-nil
        - expected-actual
        - len
        - require-error
        - suite-dont-use-pkg
        - suite-extra-assert-call
      disable:
        - float-compare
        - go-require
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/testcontainers)
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
